name: Update Radiance Branch from CVS and Build + Deploy

on:
  push:
    branches: [ cvsimport ]
  schedule:
    - cron: "0 0,6,12,18 * * *"

jobs:
  cvsimport:
    name: "Run CVSImport"
    runs-on: ubuntu-20.04
    outputs:
      HAS_NEW_COMMITS: ${{ steps.ifBuildTrigger.outputs.HAS_NEW_COMMITS }}

    steps:
      - name: Clone this repo to machine
        run: |
          git clone https://github.com/${{ github.repository }}
          cd Radiance
          git branch -a
          git checkout cvsimport
          ls
          
      - name: Install old CVSPS
        run: |
          git clone https://github.com/MingboPeng/cvsps cvsps_old
          cd cvsps_old
          make
          sudo make install
        if: "github.ref == 'refs/heads/master'"
      
      - name: Install cvsimport
        run: |
          sudo apt-get install git-cvs

      - name: Run CVS Import
        run: |
          cd Radiance
          bash cvsimport.sh

      - name: Set up build trigger
        id: ifBuildTrigger
        run: |
          cd Radiance
          git checkout master

          unset HAS_NEW_COMMITS
          if [[ "$(git status)" == *"Your branch is ahead of"* ]]; then HAS_NEW_COMMITS='true' ; fi
          echo set-output name=HAS_NEW_COMMITS::${HAS_NEW_COMMITS}
          echo ::set-output name=HAS_NEW_COMMITS::${HAS_NEW_COMMITS}

      - name: Push updates to master branch
        uses: ad-m/github-push-action@master
        with:
          directory: Radiance
          github_token: ${{ secrets.GH_TOKEN }}
          branch: master
        if: steps.ifBuildTrigger.outputs.HAS_NEW_COMMITS
  
  build_Windows:
    needs: cvsimport
    name: "Build for Windows"
    runs-on: windows-latest
    if: needs.cvsimport.outputs.HAS_NEW_COMMITS == 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: 'win64_msvc2017_64'

      - name: Install CMake 
        uses: ilammy/msvc-dev-cmd@v1
      
      - name: Build
        uses: lukka/run-cmake@v2
        with:
          cmakeGenerator: VS16Win64
          cmakeListsOrSettingsJson: CMakeListsTxtBasic
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          cmakeBuildType: Release
          buildWithCMakeArgs: "--config Release --target ALL_BUILD"
          buildDirectory: ${{ github.workspace }}/build
          buildWithCMake: true

      - name: list files
        run: |
          ls -R
        shell: bash

      - name: Zip Build Artifact
        uses: papeloto/action-zip@v1
        with:
          files: ./build/bin ./build/lib
          dest: Radiance.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Radiance_Windows
          path: Radiance.zip


  build_OSX:
    needs: cvsimport
    name: "Build for OSX"
    runs-on: macos-latest
    if: needs.cvsimport.outputs.HAS_NEW_COMMITS == 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Install CMake 
        uses: ilammy/msvc-dev-cmd@v1

      
      - name: Build
        uses: lukka/run-cmake@v2
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtBasic
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          cmakeBuildType: Release
          buildWithCMakeArgs: "--config Release"
          buildDirectory: ${{ github.workspace }}/build
          buildWithCMake: true


      - name: list files
        run: |
          ls -R
        shell: bash

      - name: Zip Build Artifact
        run: |
          zip -r Radiance.zip ./build/bin ./build/lib
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Radiance_OSX
          path: Radiance.zip


 
  build_Linux:
    needs: cvsimport
    name: "Build for Linux"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Install CMake 
        uses: ilammy/msvc-dev-cmd@v1
      

      - name: set dev packages
        run: |
          sudo apt install libglu1-mesa-dev freeglut3-dev

      - name: Build
        uses: lukka/run-cmake@v2
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtBasic
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          cmakeBuildType: Release
          buildWithCMakeArgs: "--config Release"
          buildDirectory: ${{ github.workspace }}/build
          buildWithCMake: true

      - name: list files
        run: |
          ls -R
        shell: bash

      - name: Zip Build Artifact
        run: |
          zip -r Radiance.zip ./build/bin ./build/lib

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Radiance_Linux
          path: Radiance.zip
