name: Update Radiance Branch from CVS

on:
  push:
    branches: [ cvsimport ]
  schedule:
    - cron: "0 0,6,12,18 * * *"

jobs:
  build:
    name: "Update Radiance from CVS"
    runs-on: ubuntu-20.04

    steps:
      - name: Clone this repo to machine
        run: |
          git clone https://github.com/${{ github.repository }}
          cd Radiance
          git branch -a
          git checkout cvsimport
          ls
          
      - name: Install old CVSPS
        run: |
          git clone https://github.com/MingboPeng/cvsps cvsps_old
          cd cvsps_old
          make
          sudo make install
      
      - name: Install cvsimport
        run: |
          sudo apt-get install git-cvs

      - name: Run CVS Import
        run: |
          cd Radiance
          bash cvsimport.sh
          git checkout master
      
      - name: Push updates to master branch
        uses: ad-m/github-push-action@master
        with:
          directory: Radiance
          github_token: ${{ secrets.GH_TOKEN }}
          branch: master





